In [237]:
import numpy as np
def get_vander_matrixx(a_list,order=False):
    newlist = []
    if(order):
        for i in range(0,len(a_list)):
            temp = [];
            for j in range(0,len(a_list)):
                value = a_list[i]**j
                temp.append(value)
            newlist.append(temp)
        return np.array(newlist)
    else:
        for i in range(0,len(a_list)):
            pow = len(a_list)-i-1
            temp = []
            for j in range(0,len(a_list)):
                value = a_list[j]**pow
                temp.append(value)
            newlist.append(temp)
        return np.array(newlist).transpose()

In [244]:
ll =[1,2,3,4,5]
get_vander_matrixx(ll,False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [245]:
get_vander_matrixx(ll,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [191]:
np.vander(ll,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [192]:
np.vander(ll,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])